services:
  # DB
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - webnet

  # WordPress
  wordpress:
    image: wordpress:6.8.3-php8.1-apache
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
    volumes:
      - wp_uploads:/var/www/html/wp-content/uploads
    restart: always
    depends_on:
      - mariadb
    networks:
      - webnet

volumes:
  db_data:
  wp_uploads:

networks:
  webnet:
